"""initial 14 table schema

Revision ID: 60a731298ee8
Revises: 50e196c07aa5
Create Date: 2026-08-14 19:10:00.232624

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60a731298ee8'
down_revision: Union[str, Sequence[str], None] = '50e196c07aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('paper_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('authors', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('page_count', sa.SmallInteger(), nullable=True),
    sa.Column('processing_status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('processing_phase', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('extractable_text_ratio', sa.REAL(), nullable=True),
    sa.Column('unreadable_pages', sa.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('security_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concept_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("processing_status IN ('queued', 'processing', 'ready', 'partially_ready', 'failed')", name=op.f('ck_papers_processing_status')),
    sa.CheckConstraint('extractable_text_ratio IS NULL OR (extractable_text_ratio BETWEEN 0 AND 1)', name=op.f('ck_papers_extractable_ratio_range')),
    sa.CheckConstraint('page_count IS NULL OR page_count > 0', name=op.f('ck_papers_page_count_positive')),
    sa.CheckConstraint('year IS NULL OR (year BETWEEN 1900 AND 2100)', name=op.f('ck_papers_year_range')),
    sa.PrimaryKeyConstraint('paper_id', name=op.f('pk_papers')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_papers_content_hash'))
    )
    op.create_index('ix_papers_processing_status_live', 'papers', ['processing_status'], unique=False, postgresql_where=sa.text("processing_status NOT IN ('ready', 'failed')"))
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('auth_subject', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_demo_account', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('auth_subject', name='uq_users_auth_subject')
    )
    op.create_index('uq_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('concepts',
    sa.Column('concept_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('understanding_score', sa.REAL(), nullable=True),
    sa.Column('score_confidence', sa.REAL(), nullable=True),
    sa.Column('evidence_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('effective_style', sa.Text(), nullable=True),
    sa.Column('source_paper_ids', sa.ARRAY(sa.UUID()), server_default=sa.text("'{}'::uuid[]"), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reinforced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_override_score', sa.REAL(), nullable=True),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("effective_style IS NULL OR effective_style IN ('formal', 'intuitive', 'numerical', 'analogical', 'visual_verbal', 'code', 'contrastive')", name=op.f('ck_concepts_effective_style')),
    sa.CheckConstraint('evidence_count >= 0', name=op.f('ck_concepts_evidence_count_non_negative')),
    sa.CheckConstraint('merged_into_id <> concept_id', name=op.f('ck_concepts_no_self_merge')),
    sa.CheckConstraint('score_confidence IS NULL OR (score_confidence BETWEEN 0 AND 1)', name=op.f('ck_concepts_score_confidence_range')),
    sa.CheckConstraint('understanding_score IS NULL OR (understanding_score BETWEEN 0 AND 1)', name=op.f('ck_concepts_understanding_score_range')),
    sa.CheckConstraint('user_override_score IS NULL OR (user_override_score BETWEEN 0 AND 1)', name=op.f('ck_concepts_user_override_score_range')),
    sa.ForeignKeyConstraint(['merged_into_id'], ['concepts.concept_id'], name=op.f('fk_concepts_merged_into_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_concepts_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id', name=op.f('pk_concepts'))
    )
    op.create_index('ix_concepts_aliases', 'concepts', ['aliases'], unique=False, postgresql_using='gin')
    op.create_index('ix_concepts_embedding_hnsw', 'concepts', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('merged_into_id IS NULL'))
    op.create_index('ix_concepts_source_paper_ids', 'concepts', ['source_paper_ids'], unique=False, postgresql_using='gin')
    op.create_index('ix_concepts_user_id_understanding_score', 'concepts', ['user_id', 'understanding_score'], unique=False, postgresql_where=sa.text('merged_into_id IS NULL AND score_confidence >= 0.3'))
    op.create_index('uq_concepts_user_id_normalized_name', 'concepts', ['user_id', 'normalized_name'], unique=True, postgresql_where=sa.text('merged_into_id IS NULL'))
    op.create_table('sections',
    sa.Column('section_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('section_path', sa.String(length=200), nullable=False),
    sa.Column('section_role', sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('page_start', sa.SmallInteger(), nullable=False),
    sa.Column('page_end', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("section_role IN ('abstract', 'introduction', 'related_work', 'method', 'experiments', 'results', 'discussion', 'conclusion', 'references', 'appendix', 'unknown')", name=op.f('ck_sections_section_role')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_sections_ordinal_non_negative')),
    sa.CheckConstraint('page_start > 0 AND page_end >= page_start', name=op.f('ck_sections_page_span_valid')),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name=op.f('fk_sections_paper_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id', name=op.f('pk_sections')),
    sa.UniqueConstraint('paper_id', 'ordinal', name='uq_sections_paper_id_ordinal')
    )
    op.create_index('ix_sections_paper_id_section_role', 'sections', ['paper_id', 'section_role'], unique=False)
    op.create_table('user_paper_access',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('nickname', sa.String(length=200), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name=op.f('fk_user_paper_access_paper_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_paper_access_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'paper_id', name=op.f('pk_user_paper_access'))
    )
    op.create_index('ix_user_paper_access_paper_id', 'user_paper_access', ['paper_id'], unique=False)
    op.create_index('ix_user_paper_access_user_id_last_opened_at', 'user_paper_access', ['user_id', sa.literal_column('last_opened_at DESC')], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('chunks',
    sa.Column('chunk_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.SmallInteger(), nullable=True),
    sa.Column('page_start', sa.SmallInteger(), nullable=False),
    sa.Column('page_end', sa.SmallInteger(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('is_indexable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('char_length(content) BETWEEN 1 AND 8000', name=op.f('ck_chunks_content_length')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_chunks_ordinal_non_negative')),
    sa.CheckConstraint('page_start > 0 AND page_end >= page_start', name=op.f('ck_chunks_page_span_valid')),
    sa.CheckConstraint('token_count IS NULL OR token_count > 0', name=op.f('ck_chunks_token_count_positive')),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name=op.f('fk_chunks_paper_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], name=op.f('fk_chunks_section_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('paper_id', 'ordinal', name='uq_chunks_paper_id_ordinal')
    )
    op.create_index('ix_chunks_embedding_hnsw', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('is_indexable AND embedding IS NOT NULL'))
    op.create_index('ix_chunks_paper_id_indexable', 'chunks', ['paper_id'], unique=False, postgresql_where=sa.text('is_indexable'))
    op.create_table('quizzes',
    sa.Column('quiz_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(length=2000), nullable=False),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grounding_chunk_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('array_length(grounding_chunk_ids, 1) >= 1', name=op.f('ck_quizzes_grounding_required')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.concept_id'], name=op.f('fk_quizzes_concept_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name=op.f('fk_quizzes_paper_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_quizzes_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quiz_id', name=op.f('pk_quizzes'))
    )
    op.create_index('ix_quizzes_user_id_concept_id_created_at', 'quizzes', ['user_id', 'concept_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('active_paper_id', sa.UUID(), nullable=True),
    sa.Column('activity', sa.Text(), server_default=sa.text("'FREE'"), nullable=False),
    sa.Column('pending_quiz_id', sa.UUID(), nullable=True),
    sa.Column('active_concept_id', sa.UUID(), nullable=True),
    sa.Column('last_callback_turn', sa.Integer(), nullable=True),
    sa.Column('turn_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(activity = 'QUIZ_PENDING') = (pending_quiz_id IS NOT NULL)", name=op.f('ck_sessions_quiz_pending_consistency')),
    sa.CheckConstraint("activity IN ('FREE', 'EXPLAINING', 'QUIZ_PENDING', 'AWAITING_CLARIFICATION')", name=op.f('ck_sessions_activity')),
    sa.CheckConstraint('turn_count >= 0', name=op.f('ck_sessions_turn_count_non_negative')),
    sa.ForeignKeyConstraint(['active_concept_id'], ['concepts.concept_id'], name=op.f('fk_sessions_active_concept_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['active_paper_id'], ['papers.paper_id'], name=op.f('fk_sessions_active_paper_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pending_quiz_id'], ['quizzes.quiz_id'], name=op.f('fk_sessions_pending_quiz_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_last_activity_at', 'sessions', ['last_activity_at'], unique=False, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_index('ix_sessions_user_id_started_at', 'sessions', ['user_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('turns',
    sa.Column('turn_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.String(length=8000), nullable=True),
    sa.Column('agent_action', sa.String(length=64), nullable=True),
    sa.Column('explanation_style', sa.Text(), nullable=True),
    sa.Column('callback_concept_id', sa.UUID(), nullable=True),
    sa.Column('callback_suppressed_reason', sa.String(length=64), nullable=True),
    sa.Column('memory_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('grounding_status', sa.Text(), server_default=sa.text("'n/a'"), nullable=False),
    sa.Column('tools_called', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("explanation_style IS NULL OR explanation_style IN ('formal', 'intuitive', 'numerical', 'analogical', 'visual_verbal', 'code', 'contrastive')", name=op.f('ck_turns_explanation_style')),
    sa.CheckConstraint("grounding_status IN ('grounded', 'no_evidence', 'degraded', 'n/a')", name=op.f('ck_turns_grounding_status')),
    sa.CheckConstraint('callback_concept_id IS NULL OR memory_read', name=op.f('ck_turns_callback_requires_memory')),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name=op.f('ck_turns_input_tokens_non_negative')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_turns_latency_non_negative')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_turns_ordinal_non_negative')),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name=op.f('ck_turns_output_tokens_non_negative')),
    sa.ForeignKeyConstraint(['callback_concept_id'], ['concepts.concept_id'], name=op.f('fk_turns_callback_concept_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name=op.f('fk_turns_paper_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name=op.f('fk_turns_session_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_turns_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('turn_id', name=op.f('pk_turns')),
    sa.UniqueConstraint('session_id', 'ordinal', name='uq_turns_session_id_ordinal')
    )
    op.create_index('ix_turns_session_id_created_at', 'turns', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_turns_user_id_created_at', 'turns', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('concept_relationships',
    sa.Column('relationship_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_concept_id', sa.UUID(), nullable=False),
    sa.Column('target_concept_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.REAL(), nullable=False),
    sa.Column('discovery_method', sa.Text(), nullable=False),
    sa.Column('evidence_turn_id', sa.UUID(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("discovery_method IN ('embedding', 'model', 'user_stated')", name=op.f('ck_concept_relationships_discovery_method')),
    sa.CheckConstraint("relationship_type IN ('prerequisite_of', 'component_of', 'specialisation_of', 'contrasts_with', 'equivalent_notation', 'co_occurs_with')", name=op.f('ck_concept_relationships_relationship_type')),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_concept_relationships_confidence_range')),
    sa.CheckConstraint('source_concept_id <> target_concept_id', name=op.f('ck_concept_relationships_no_self_edge')),
    sa.ForeignKeyConstraint(['evidence_turn_id'], ['turns.turn_id'], name=op.f('fk_concept_relationships_evidence_turn_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_concept_id'], ['concepts.concept_id'], name=op.f('fk_concept_relationships_source_concept_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_concept_id'], ['concepts.concept_id'], name=op.f('fk_concept_relationships_target_concept_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_concept_relationships_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relationship_id', name=op.f('pk_concept_relationships')),
    sa.UniqueConstraint('user_id', 'source_concept_id', 'target_concept_id', 'relationship_type', name='uq_concept_relationships_edge')
    )
    op.create_index('ix_concept_relationships_user_id_source', 'concept_relationships', ['user_id', 'source_concept_id'], unique=False)
    op.create_index('ix_concept_relationships_user_id_target', 'concept_relationships', ['user_id', 'target_concept_id'], unique=False)
    op.create_table('feedback',
    sa.Column('feedback_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.Text(), nullable=False),
    sa.Column('target_turn_id', sa.UUID(), nullable=True),
    sa.Column('target_concept_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('applied_to_turn_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("feedback_type IN ('helpful', 'not_helpful', 'too_basic', 'too_advanced', 'wrong', 'style_preference')", name=op.f('ck_feedback_feedback_type')),
    sa.CheckConstraint('(target_turn_id IS NOT NULL)::int + (target_concept_id IS NOT NULL)::int = 1', name=op.f('ck_feedback_exactly_one_target')),
    sa.ForeignKeyConstraint(['applied_to_turn_id'], ['turns.turn_id'], name=op.f('fk_feedback_applied_to_turn_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_concept_id'], ['concepts.concept_id'], name=op.f('fk_feedback_target_concept_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_turn_id'], ['turns.turn_id'], name=op.f('fk_feedback_target_turn_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_feedback_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('pk_feedback'))
    )
    op.create_index('ix_feedback_user_id_created_at', 'feedback', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('attempt_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('answer_text', sa.String(length=4000), nullable=False),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('missing_elements', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('grader_confidence', sa.REAL(), nullable=True),
    sa.Column('grading_error', sa.String(length=200), nullable=True),
    sa.Column('attempt_no', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("grade IS NULL OR grade IN ('correct', 'partial', 'incorrect')", name=op.f('ck_quiz_attempts_grade')),
    sa.CheckConstraint('(grade IS NULL) = (grading_error IS NOT NULL)', name=op.f('ck_quiz_attempts_grade_or_error')),
    sa.CheckConstraint('attempt_no >= 1', name=op.f('ck_quiz_attempts_attempt_no_positive')),
    sa.CheckConstraint('grader_confidence IS NULL OR (grader_confidence BETWEEN 0 AND 1)', name=op.f('ck_quiz_attempts_grader_confidence_range')),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], name=op.f('fk_quiz_attempts_quiz_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.turn_id'], name=op.f('fk_quiz_attempts_turn_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_quiz_attempts_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id', name=op.f('pk_quiz_attempts')),
    sa.UniqueConstraint('quiz_id', 'attempt_no', name='uq_quiz_attempts_quiz_id_attempt_no')
    )
    op.create_table('turn_retrievals',
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('similarity', sa.REAL(), nullable=False),
    sa.Column('retrieval_query', sa.String(length=1000), nullable=True),
    sa.Column('was_cited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('citation_marker', sa.String(length=16), nullable=True),
    sa.CheckConstraint('(citation_marker IS NOT NULL) = was_cited', name=op.f('ck_turn_retrievals_marker_matches_cited')),
    sa.CheckConstraint('rank >= 1', name=op.f('ck_turn_retrievals_rank_positive')),
    sa.CheckConstraint('similarity BETWEEN -1 AND 1', name=op.f('ck_turn_retrievals_similarity_range')),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('fk_turn_retrievals_chunk_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.turn_id'], name=op.f('fk_turn_retrievals_turn_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('turn_id', 'chunk_id', name=op.f('pk_turn_retrievals'))
    )
    op.create_index('ix_turn_retrievals_chunk_id', 'turn_retrievals', ['chunk_id'], unique=False)
    op.create_index('ix_turn_retrievals_turn_id_cited', 'turn_retrievals', ['turn_id'], unique=False, postgresql_where=sa.text('was_cited'))
    op.create_table('observations',
    sa.Column('observation_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('signal_source', sa.Text(), nullable=False),
    sa.Column('weight', sa.REAL(), nullable=False),
    sa.Column('style_in_play', sa.Text(), nullable=True),
    sa.Column('resolves_observation_id', sa.UUID(), nullable=True),
    sa.Column('quiz_attempt_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("signal_source IN ('explicit', 'implicit', 'quiz', 'user_stated', 'system')", name=op.f('ck_observations_signal_source')),
    sa.CheckConstraint("signal_type IN ('explicit_confusion', 'implicit_confusion', 'explicit_understanding', 'quiz_correct', 'quiz_partial', 'quiz_incorrect', 'applied_correctly', 'user_stated_known', 'user_stated_unknown', 'reinforcement')", name=op.f('ck_observations_signal_type')),
    sa.CheckConstraint("style_in_play IS NULL OR style_in_play IN ('formal', 'intuitive', 'numerical', 'analogical', 'visual_verbal', 'code', 'contrastive')", name=op.f('ck_observations_style_in_play')),
    sa.CheckConstraint('resolves_observation_id <> observation_id', name=op.f('ck_observations_no_self_resolution')),
    sa.CheckConstraint('weight BETWEEN 0 AND 1', name=op.f('ck_observations_weight_range')),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.concept_id'], name=op.f('fk_observations_concept_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.attempt_id'], name=op.f('fk_observations_quiz_attempt_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolves_observation_id'], ['observations.observation_id'], name=op.f('fk_observations_resolves_observation_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name=op.f('fk_observations_session_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.turn_id'], name=op.f('fk_observations_turn_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_observations_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observation_id', name=op.f('pk_observations'))
    )
    op.create_index('ix_observations_concept_id_resolutions', 'observations', ['concept_id'], unique=False, postgresql_where=sa.text('resolves_observation_id IS NOT NULL'))
    op.create_index('ix_observations_turn_id', 'observations', ['turn_id'], unique=False)
    op.create_index('ix_observations_user_id_concept_id_observed_at', 'observations', ['user_id', 'concept_id', sa.literal_column('observed_at DESC')], unique=False)
    op.create_index('ix_observations_user_id_observed_at', 'observations', ['user_id', sa.literal_column('observed_at DESC')], unique=False)
    # ### end Alembic commands ###

    # --- Append-only enforcement (ARCHITECTURE 4.7, 4.11, 4.13) -----------
    # The evidence tables are the audit trail the learner model is replayed
    # from. Revoking UPDATE/DELETE from the app role is the other half of this;
    # the trigger is what survives a role misconfiguration.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'table % is append-only', TG_TABLE_NAME
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("turns", "observations", "quiz_attempts"):
        op.execute(
            f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION reject_mutation();
            """
        )

    # --- papers.updated_at ------------------------------------------------
    # Ingestion advances processing_phase from several places; a trigger keeps
    # updated_at honest without every call site remembering to set it.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER papers_touch_updated_at
        BEFORE UPDATE ON papers
        FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS papers_touch_updated_at ON papers")
    op.execute("DROP FUNCTION IF EXISTS touch_updated_at()")
    for table in ("turns", "observations", "quiz_attempts"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS reject_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observations_user_id_observed_at', table_name='observations')
    op.drop_index('ix_observations_user_id_concept_id_observed_at', table_name='observations')
    op.drop_index('ix_observations_turn_id', table_name='observations')
    op.drop_index('ix_observations_concept_id_resolutions', table_name='observations', postgresql_where=sa.text('resolves_observation_id IS NOT NULL'))
    op.drop_table('observations')
    op.drop_index('ix_turn_retrievals_turn_id_cited', table_name='turn_retrievals', postgresql_where=sa.text('was_cited'))
    op.drop_index('ix_turn_retrievals_chunk_id', table_name='turn_retrievals')
    op.drop_table('turn_retrievals')
    op.drop_table('quiz_attempts')
    op.drop_index('ix_feedback_user_id_created_at', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_concept_relationships_user_id_target', table_name='concept_relationships')
    op.drop_index('ix_concept_relationships_user_id_source', table_name='concept_relationships')
    op.drop_table('concept_relationships')
    op.drop_index('ix_turns_user_id_created_at', table_name='turns')
    op.drop_index('ix_turns_session_id_created_at', table_name='turns')
    op.drop_table('turns')
    op.drop_index('ix_sessions_user_id_started_at', table_name='sessions')
    op.drop_index('ix_sessions_last_activity_at', table_name='sessions', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_table('sessions')
    op.drop_index('ix_quizzes_user_id_concept_id_created_at', table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index('ix_chunks_paper_id_indexable', table_name='chunks', postgresql_where=sa.text('is_indexable'))
    op.drop_index('ix_chunks_embedding_hnsw', table_name='chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('is_indexable AND embedding IS NOT NULL'))
    op.drop_table('chunks')
    op.drop_index('ix_user_paper_access_user_id_last_opened_at', table_name='user_paper_access', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_user_paper_access_paper_id', table_name='user_paper_access')
    op.drop_table('user_paper_access')
    op.drop_index('ix_sections_paper_id_section_role', table_name='sections')
    op.drop_table('sections')
    op.drop_index('uq_concepts_user_id_normalized_name', table_name='concepts', postgresql_where=sa.text('merged_into_id IS NULL'))
    op.drop_index('ix_concepts_user_id_understanding_score', table_name='concepts', postgresql_where=sa.text('merged_into_id IS NULL AND score_confidence >= 0.3'))
    op.drop_index('ix_concepts_source_paper_ids', table_name='concepts', postgresql_using='gin')
    op.drop_index('ix_concepts_embedding_hnsw', table_name='concepts', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('merged_into_id IS NULL'))
    op.drop_index('ix_concepts_aliases', table_name='concepts', postgresql_using='gin')
    op.drop_table('concepts')
    op.drop_index('uq_users_email', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_table('users')
    op.drop_index('ix_papers_processing_status_live', table_name='papers', postgresql_where=sa.text("processing_status NOT IN ('ready', 'failed')"))
    op.drop_table('papers')
    # ### end Alembic commands ###
